spring:
  application:
    name: Interview-Project-Server

  datasource:
    url: jdbc:postgresql://localhost:5432/interview_application
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver